# .github/workflows/ci.yml
name: CI
on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Gerekiyorsa Black'i kaldırın; Ruff 'format' da yapabilir
      - run: pip install ruff pytest

      - name: Ruff (statik analiz)
        run: ruff check .

      # İsterseniz otomatik düzeltme:
      # run: ruff check --fix .

      - name: Pytest
        run: pytest -q || echo "no tests yet"