name: CI
on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install black ruff pytest

      - name: Black (format)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest
        run: pytest -q || echo "tests will be added later"
