name: CI           # GitHub aracında görünen ad

on:                # Ne zaman çalışsın?
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-test:
    runs-on: ubuntu-latest          # Sanal makine
    steps:
      # 1) Kodu çek
      - uses: actions/checkout@v4

      # 2) Python ortamı
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3) Bağımlılıkları yükle
      - run: pip install black ruff pytest

      # 4) Lint (stil) kontrolü
      - name: Black (format)
        run: black --check .

      - name: Ruff (statik analiz)
        run: ruff .

      # 5) Test aşaması
      - name: Pytest
        run: |
          pytest -q || echo "No tests yet – skipping failure"